version: '3.8'

services:
  db:
    image: postgres:18.1
    container_name: nest-practice-db
    env_file: './.env'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - Nest-Practice-Postgres-Volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: nest-practice-redis
    ports: 
      - "6379:6379"
    volumes:
      - Nest-Practice-Redis-Volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  Nest-Practice-Postgres-Volume:
  Nest-Practice-Redis-Volume: