name: Test Workflow
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 抓取程式碼
        uses: actions/checkout@v6
      - name: 安裝Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: 安裝依賴
        run: npm ci
      - name: 跑測試
        run: npm run test
